### ISSUE TITLE
Storage statements and deallocating locals on return

### ISSUE THREAD

**Issue by JakobDegen** [RalfJung/minirust#4]
The `Return` terminator currently fails to deallocate any locals. This makes it possible to write a minirust program which returns a reference to a local but is DB - that feels like a bug. Miri is not affected by this because it tracks whether locals are allocated/deallocated explicitly, and then deallocates exactly those that it needs to. Is this what we should do as well? If not, how do we know which locals to deallocate, given that some of them may already have been deallocated by `StorageDead`?

Additionally, MIR has a rule that locals for which there does not appear a storage statement anywhere in the function are automatically allocated at function call time. Do we want to support this?

**Comment by digama0** [comment]
If MIR is already deallocating all locals explicitly, we could make that mandatory by saying that `Return` is UB if all places (except the return place?) have not been previously deallocated with `StorageDead`.

**Comment by JakobDegen** [comment]
MIR is not deallocation explicitly though, as a matter of fact it deallocates everything that wasn't deallocated explicitly implicitly. This is what LLVM does too, `alloca` allocations are gone at the end of the function, no `lifetime.end` required

**Comment by digama0** [comment]
In that case, I think you are right, there needs to be a loop like
```rust
        for p in self.cur_frame_mut().locals {
            let type: Type = ??;
            self.mem.deallocate(p, type.size(), type.align())?;
        }
```
Only: we can't do this, because we don't know at what type to deallocate the locals. This probably has to do with the fact that places don't come with explicit types in minirust, unlike Miri, which moves the type ascriptions around. I think this means that minirust needs explicit deallocation for all locals.

**Comment by JakobDegen** [comment]
I don't think the types are the problem, we can tack them onto the `locals`, ie have `Locals` be a `Map<LocalName, LocalInfo>` where

```rust
struct LocalInfo {
    place: Place,
    type: Ty,
}
```

The problem is moreso that this is a double-free of locals for which there is `StorageDead`. The only way I see to fix that is to also make the `place` an `Option<Place>`, effectively storing whether the local is allocated or not.

> I think this means that minirust needs explicit deallocation for all locals.

I would be somewhat strongly against this. Imo we should be able to prove a theorem that all minirust programs can be soundly compiled to hardware (in roughly the way we want them to) and this would prohibit that.

**Comment by digama0** [comment]
The issue of only freeing things that are still live is easy enough, the for loop I gave solves that problem since `StorageDead` already removes the local from the list (take a look at the current code for it).

The downside of storing types in the `LocalInfo` is that "memory contains types", which @RalfJung may object to. I'm neutral on the suggestion. Should `StorageDead` require that the provided type match the type of the local, or should it not have a type at all?

**Comment by JakobDegen** [comment]
> The issue of only freeing things that are still live is easy enough, the for loop I gave solves that problem since StorageDead already removes the local from the list (take a look at the current code for it).

Ah, sorry, I missed that. That makes sense.

> Should StorageDead require that the provided type match the type of the local, or should it not have a type at all?

Not requiring a type seems reasonable. I also don't think this is typed memory. Indeed, the `mem::deallocate` function continues to accept deallocations with any matching layout, regardless of type. This is just lang level things enforcing that the deallocate uses the right type for stack variables.

> I don't see how it would. It's just one more ghost operation which gets removed during lowering to LLVM. If the semantics of LLVM lifetime.end say that it isn't necessary to end locals before a return, then that's a fairly simple optimization pass (I assume it is not harmful to have those lifetime.ends anyway so it is just a straight optimization relative to LLVM semantics.)

Ah, I suppose I may not have understood what you meant. I assumed you meant that we leave `Return` as is, which is a problem because then some locals may not get freed at all. The alternative is that we have a
```rust
if locals.keys() != [return_place] {
    throw_ub!("Failed to deallocate local")
}
```
in `Return`, but this seems quite a bit out of line with MIR

**Comment by digama0** [comment]
> The alternative is that we have a
> 
> ```rust
> if locals.keys() != [return_place] {
>     throw_ub!("Failed to deallocate local")
> }
> ```
> 
> in `Return`, but this seems quite a bit out of line with MIR

Yes, this was my suggestion (in conjunction with emitting StorageDead for all locals beforehand). As with double-StorageDead, a violation here is a mir generation bug, so I'm not sure whether it is best to categorize it as UB, NB, or "spec bug" (i.e. panic in the semantics), but it would make sense to do the same thing here as with double-dead and double-live locals.

**Comment by RalfJung** [comment]
> The Return terminator currently fails to deallocate any locals

Ah, good point. I added a proposal for how that could be handled in 4f151ab. It requires `StorageDead` for all non-argument locals, or else causes a spec bug.

> Additionally, MIR has a rule that locals for which there does not appear a storage statement anywhere in the function are automatically allocated at function call time. Do we want to support this?

I don't think so, I feel like this should be explicit but we just avoid it do make MIR not blow up in size. To some extent this rule exists only because StorageLive annotations were partial and buggy when Miri gained support for then, so I made it work with whatever we had. I am not sure if this is even a good rule.

> EDIT: The current semantics say that it is a "spec bug" to ever double-StorageDead, but this doesn't really make sense to me since MIR is an input to the semantics and two StorageDead in a row are clearly a possible (but ill formed?) MIR input.

My thinking was that this might be considered ill-formed, and the spec does not have to work for ill-formed inputs. I have not precisely defined "well-formed MiniRust" yet.

However, actually ensuring this for the storage annotations will require a dataflow analysis, which is annoying. OTOH, I think it is definitely a rustc bug and not a user bug if we have such incorrect annotations, so making it UB seems wrong. Maybe I should add "invalid program" errors, like Miri has, though I am not sure how different that would really be from a panic. I think "well-formed MiniRust" might just have to contain a dataflow analysis.

**Comment by bjorn3** [comment]
> > Additionally, MIR has a rule that locals for which there does not appear a storage statement anywhere in the function are automatically allocated at function call time. Do we want to support this?
> 
> I don't think so, I feel like this should be explicit but we just avoid it to make MIR not blow up in size. To some extent this rule exists only because StorageLive annotations were partial and buggy when Miri gained support for then, so I made it work with whatever we had. I am not sure if this is even a good rule.

When optimizations are disabled, StorageLive and StorageDead are erased before codegen. I also believe neither StorageLive nor StorageDead is generated for the unwinding path.

**Comment by JakobDegen** [comment]
> I have not precisely defined "well-formed MiniRust" yet.

Somewhat off-topic, but I actually want to argue that we should maybe not focus too much on doing this. I assume we'll eventually merge MiniRust with a-mir-formality, at which point this will need to redone (at least to some extent) anyway.

> My thinking was that this might be considered ill-formed

So, I agree that this works, but what is the benefit of it? Why not just deallocate everything on `Return`? Storing the type with the locals seems fairly simple compared to including a dataflow analysis for well-formedness and aligns more with MIR and LLVM,

**Comment by digama0** [comment]
> > My thinking was that this might be considered ill-formed
> 
> So, I agree that this works, but what is the benefit of it? Why not just deallocate everything on `Return`? Storing the type with the locals seems fairly simple compared to including a dataflow analysis for well-formedness and aligns more with MIR and LLVM,

I don't think there is necessarily any need for the well-formedness to be expressed explicitly in minirust except insofar as it affects the runtime semantics. In this case, I would express it as a `throw_ill_formed!()` similar to `throw_ub` which is already used. This would define a set of well formedness checks simply from the assertion "well-formed MIR => every execution cannot hit `throw_ill_formed!()`", but I wouldn't take this as the *definition* of well formed, but rather as a constraint on well formedness. a-mir-formality is better placed to give the actual definition of MIR well-formedness.

**Comment by RalfJung** [comment]
> Somewhat off-topic, but I actually want to argue that we should maybe not focus too much on doing this. I assume we'll eventually merge MiniRust with a-mir-formality, at which point this will need to redone (at least to some extent) anyway.

I think I want to to it soon since currently it is not very clear whether some `panic!` is justified or not.
Also while I hope a-mir-formality will one day have a (basically) equivalent semantics, I find it hard to predict whether that will make MiniRust redundant -- I feel like MiniRust is something I can much more easily show to an advanced Rust programmer and they will understand what happens, whereas I have trouble parsing even the basic parts of a-mir-formality despite having tons of Rust and formal methods experience.

> So, I agree that this works, but what is the benefit of it? Why not just deallocate everything on Return? Storing the type with the locals seems fairly simple compared to including a dataflow analysis for well-formedness and aligns more with MIR and LLVM,

Yeah, well, I wanted to see how far I can get with minimal type information.
But storing a `Map<LocalName, Type>` in the syntax of a `Function` is probably what most readers will expect anyway, so yeah it wouldn't be too bad. In fact I would only need `Map<LocalName, Layout>`. It's just a bit odd that it would not contain the return local...

**Comment by JakobDegen** [comment]
Well, one of the reasons I'm in favor of this is because if we do allow deallocating on `Return`, then we could also make return accept a `ValueExpr`. Again, this is not what is done in MIR, but it's closer to Rust and seems much easier to reason about. This would also get rid of the need to put a `Finalize` in the caller after the call - that would be possible, but always felt weird to me because this does not represent a contract that the caller is responsible for upholding.

**Comment by digama0** [comment]
> Also while I hope a-mir-formality will one day have a (basically) equivalent semantics, I find it hard to predict whether that will make MiniRust redundant -- I feel like MiniRust is something I can much more easily show to an advanced Rust programmer and they will understand what happens, whereas I have trouble parsing even the basic parts of a-mir-formality despite having tons of Rust and formal methods experience.

By the way, this was also my initial impression of a-mir-formality, but it got a bit better after reading some tutorials on racket and PLT redex. I am now of the opinion that it suffices for now but ultimately we will probably want to actually write the whole thing in a custom language tailored for the needs of the spec which maybe looks like a mashup of Rust and formal proof rules a la redex. In any case, the syntax question is not super important in the long term and in the short term having basic scope checking and type checking is useful so I'm not really against the choice of redex anymore.

**Comment by RalfJung** [comment]
Return place handling in MIR is one of its subtler aspects so I think I also want to have it here. It's easy to compile "returns a value" to destination-passing style, but the other direction is hard.

> By the way, this was also my initial impression of a-mir-formality, but it got a bit better after reading some tutorials on racket and PLT redex. I am now of the opinion that it suffices for now but ultimately we will probably want to actually write the whole thing in a custom language tailored for the needs of the spec which maybe looks like a mashup of Rust and formal proof rules a la redex. In any case, the syntax question is not super important in the long term and in the short term having basic scope checking and type checking is useful so I'm not really against the choice of redex anymore.

Agreed! I juts need to spend that time at some point.

**Comment by RalfJung** [comment]
> This would also get rid of the need to put a Finalize in the caller after the call - that would be possible, but always felt weird to me because this does not represent a contract that the caller is responsible for upholding.

Yeah, this is the caller telling the compiler about assumptions it makes about the callee behavior.
This is similar to the `Finalize` (and `Retag`) on all arguments at the top of a function. So I don't think this is particularly strange.

**Comment by RalfJung** [comment]
With 4b38e39, we deallocate all remaining locals on `Return`. I think the issue can be closed then?

FWIW I am not 100% satisfied with the return place treatment, but since I want to keep the destination passing style I have not found a nice solution yet:
- either the return local is the only one not deallocated in `Return` (so it's a special case there)
- or it is the only one not listed in `func.locals` (so it's a special case at least during well-formedness checking)
- or we actually allocate a fresh return place on `Call`, remember the original return place, and do a copy on `Return` (but then we have to remember more stuff in `StackFrame`, and more importantly we are no longer obviously doing destination passing style -- though I anyway want to have aliasing restrictions that mean it doesn't make a difference whether we put the return value into the destination immediately or on `Return`)

**Comment by digama0** [comment]
I think option 1 is the closest to MIR, but option 2 is the easiest one for readability. What happens if you `StorageLive` / `StorageDead` the return place? It seems reasonable to just say that you aren't allowed to touch it at all with these commands, in which case nothing has to change in option 2.

**Comment by RalfJung** [comment]
Another point that bothers me is that `Call` passes arguments by value and implicitly allocates a place for them, but nothing comparable happens for the return place.

> What happens if you StorageLive / StorageDead the return place?

I would say you're not allowed to use these on argument and return places.

> in which case nothing has to change in option 2.

Well, except that `ret` is the one local you are allowed to use in a function that is not listed in `locals`. That is also very odd.

**Comment by digama0** [comment]
I was actually thinking that `ret` could be a place value which is resolved in the parent frame, in which case there is no actual copy occurring, a change to it would actually change data up the stack.

**Comment by RalfJung** [comment]
> If ret is not in the locals map, place expressions could have a variant like ReturnPlace | Local(LocalId) | projections... so that the difference is maintained in the type system.

Then we also need a `ret` in the `StackFrame` though.
But yeah maybe it is a mistake to try and treat the return place like the other locals...

**Comment by JakobDegen** [comment]
Why are we trying to do destination passing anyway? It seems to be the cause of the problems here, and it's not even what I've suggested in the docs for MIR:

> Like function calls, the exact semantics of returns in Rust are unclear. Returning very likely at least assigns the value currently in the return place (`_0`) to the place specified in the associated Call terminator in the calling function, as if assigned via `dest = move _0`.

**Comment by digama0** [comment]
I assume the reason *MIR* does destination passing is because it works more naturally with deaggregation. Are there any observable differences compared to just `Return(ValueExpr)` and doing the copy in the `Call` operation?

**Comment by JakobDegen** [comment]
I don't think MIR does destination passing style, at least not as I've documented it. MIR does copies on returns. Codegen then turns this into destination passing because we have MIR semantics that make this a sound optimization.

**Comment by RalfJung** [comment]
That's fair, this is also more symmetric with `Assign` (which would be correct even for overlapping LHS and RHS, but we will use aliasing constraints to ensure they do not overlap).

So that is the approach I am using now. The argument passing is still somewhat annoying (since the caller provides values but the callee needs places), but I can't think of a way to make this more elegant. We could ask the caller to provide places but then we need so many more temporaries, that just seems silly...

**Comment by RalfJung** [comment]
Since nobody objected when I said this issue can be closed, I am going to close it. :)  Feel free to reopen or open a new issue if you think there is still something that needs to be addressed.
